package infrastructure

import "encoding/json"

// schemaDocument serializes code-owned declarations, never runtime assets.
func schemaDocument(definition map[string]any) []byte {
	document, err := json.MarshalIndent(definition, "", "  ")
	if err != nil {
		panic("invalid SDK schema declaration")
	}
	return append(document, '\n')
}

func peerDirectoryDefinition() map[string]any {
	return map[string]any{"$schema": "https://json-schema.org/draft/2020-12/schema",
		"$id":                  "https://liapoldus.github.io/spec/plugin-sdk/v2/peer-directory.schema.json",
		"title":                "Plugin SDK peer directory v1",
		"type":                 "object",
		"additionalProperties": false,
		"required":             []any{"contractVersion", "generation", "issuedAt", "expiresAt", "caller", "links"},
		"properties": map[string]any{"contractVersion": map[string]any{"const": "liapoldus.plugin-sdk.peer-directory.v1"},
			"generation": map[string]any{"$ref": "#/$defs/identifier"},
			"issuedAt": map[string]any{"type": "string",
				"format": "date-time",
			},
			"expiresAt": map[string]any{"type": "string",
				"format": "date-time",
			},
			"caller": map[string]any{"$ref": "#/$defs/replicaIdentity"},
			"links": map[string]any{"type": "array",
				"maxItems": 256,
				"items":    map[string]any{"$ref": "#/$defs/link"},
			},
		},
		"$defs": map[string]any{"identifier": map[string]any{"type": "string",
			"minLength": 1,
			"maxLength": 256,
			"pattern":   "^[A-Za-z0-9._~-]+$",
			"not":       map[string]any{"enum": []any{".", ".."}},
		},
			"contractId": map[string]any{"type": "string",
				"minLength": 1,
				"maxLength": 256,
				"pattern":   "^[A-Za-z0-9._:/-]+$",
			},
			"semver": map[string]any{"type": "string",
				"maxLength": 128,
				"pattern":   "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)(-[0-9A-Za-z-]+(\\.[0-9A-Za-z-]+)*)?(\\+[0-9A-Za-z-]+(\\.[0-9A-Za-z-]+)*)?$",
			},
			"digest": map[string]any{"type": "string",
				"pattern": "^[a-f0-9]{64}$",
			},
			"replicaIdentity": map[string]any{"type": "object",
				"additionalProperties": false,
				"required":             []any{"instanceId", "replicaId", "incarnationId", "placementId"},
				"properties": map[string]any{"instanceId": map[string]any{"$ref": "#/$defs/identifier"},
					"replicaId":     map[string]any{"$ref": "#/$defs/identifier"},
					"incarnationId": map[string]any{"$ref": "#/$defs/identifier"},
					"placementId":   map[string]any{"$ref": "#/$defs/identifier"},
				},
			},
			"peerContractRange": map[string]any{"type": "object",
				"additionalProperties": false,
				"required":             []any{"contractId", "minimumVersion", "maximumVersionExclusive"},
				"properties": map[string]any{"contractId": map[string]any{"$ref": "#/$defs/contractId"},
					"minimumVersion":          map[string]any{"$ref": "#/$defs/semver"},
					"maximumVersionExclusive": map[string]any{"$ref": "#/$defs/semver"},
				},
			},
			"peerContractVersion": map[string]any{"type": "object",
				"additionalProperties": false,
				"required":             []any{"contractId", "version", "sha256"},
				"properties": map[string]any{"contractId": map[string]any{"$ref": "#/$defs/contractId"},
					"version": map[string]any{"$ref": "#/$defs/semver"},
					"sha256":  map[string]any{"$ref": "#/$defs/digest"},
				},
			},
			"replica": map[string]any{"type": "object",
				"additionalProperties": false,
				"required":             []any{"identity", "endpoint", "eligibility", "eligibleUntil", "weight", "peerContracts"},
				"properties": map[string]any{"identity": map[string]any{"$ref": "#/$defs/replicaIdentity"},
					"endpoint": map[string]any{"type": "string",
						"maxLength": 2048,
					},
					"eligibility": map[string]any{"enum": []any{"ready", "not-ready", "draining", "lease-expired", "fenced", "incompatible"}},
					"eligibleUntil": map[string]any{"type": []any{"string", "null"},
						"format": "date-time",
					},
					"weight": map[string]any{"type": "integer",
						"minimum": 1,
						"maximum": 100,
					},
					"peerContracts": map[string]any{"type": "array",
						"maxItems": 64,
						"items":    map[string]any{"$ref": "#/$defs/peerContractVersion"},
					},
				},
				"allOf": []any{map[string]any{"if": map[string]any{"properties": map[string]any{"eligibility": map[string]any{"const": "ready"}},
					"required": []any{"eligibility"},
				},
					"then": map[string]any{"properties": map[string]any{"endpoint": map[string]any{"minLength": 1},
						"eligibleUntil": map[string]any{"type": "string"},
					},
					},
					"else": map[string]any{"properties": map[string]any{"endpoint": map[string]any{"const": ""},
						"eligibleUntil": map[string]any{"const": nil},
					},
					},
				}},
			},
			"link": map[string]any{"type": "object",
				"additionalProperties": false,
				"required":             []any{"linkId", "targetInstanceId", "placementRule", "carrier", "securityProfile", "requiredPeerContracts", "replicas"},
				"properties": map[string]any{"linkId": map[string]any{"$ref": "#/$defs/identifier"},
					"targetInstanceId": map[string]any{"$ref": "#/$defs/identifier"},
					"placementRule":    map[string]any{"enum": []any{"same-placement", "remote"}},
					"carrier":          map[string]any{"enum": []any{"tcp", "quic", "unix", "windows-named-pipe"}},
					"securityProfile":  map[string]any{"const": "mtls"},
					"requiredPeerContracts": map[string]any{"type": "array",
						"maxItems": 64,
						"items":    map[string]any{"$ref": "#/$defs/peerContractRange"},
					},
					"replicas": map[string]any{"type": "array",
						"maxItems": 512,
						"items":    map[string]any{"$ref": "#/$defs/replica"},
					},
				},
			},
		},
	}
}

func replicaLifecycleDefinition() map[string]any {
	return map[string]any{"$schema": "https://json-schema.org/draft/2020-12/schema",
		"$id":   "https://liapoldus.github.io/spec/plugin-sdk/v2/replica-lifecycle.schema.json",
		"title": "Plugin SDK replica lifecycle v2 DTOs",
		"$defs": map[string]any{"identifier": map[string]any{"type": "string",
			"minLength": 1,
			"maxLength": 256,
			"pattern":   "^[A-Za-z0-9._~-]+$",
			"not":       map[string]any{"enum": []any{".", ".."}},
		},
			"contractId": map[string]any{"type": "string",
				"minLength": 1,
				"maxLength": 256,
				"pattern":   "^[A-Za-z0-9._:/-]+$",
			},
			"semver": map[string]any{"type": "string",
				"maxLength": 128,
				"pattern":   "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)(-[0-9A-Za-z-]+(\\.[0-9A-Za-z-]+)*)?(\\+[0-9A-Za-z-]+(\\.[0-9A-Za-z-]+)*)?$",
			},
			"digest": map[string]any{"type": "string",
				"pattern": "^[a-f0-9]{64}$",
			},
			"identity": map[string]any{"type": "object",
				"additionalProperties": false,
				"required":             []any{"instanceId", "replicaId", "incarnationId", "placementId"},
				"properties": map[string]any{"instanceId": map[string]any{"$ref": "#/$defs/identifier"},
					"replicaId":     map[string]any{"$ref": "#/$defs/identifier"},
					"incarnationId": map[string]any{"$ref": "#/$defs/identifier"},
					"placementId":   map[string]any{"$ref": "#/$defs/identifier"},
				},
			},
			"contractVersion": map[string]any{"type": "object",
				"additionalProperties": false,
				"required":             []any{"contractId", "version", "sha256"},
				"properties": map[string]any{"contractId": map[string]any{"$ref": "#/$defs/contractId"},
					"version": map[string]any{"$ref": "#/$defs/semver"},
					"sha256":  map[string]any{"$ref": "#/$defs/digest"},
				},
			},
			"contractRange": map[string]any{"type": "object",
				"additionalProperties": false,
				"required":             []any{"contractId", "minimumVersion", "maximumVersionExclusive"},
				"properties": map[string]any{"contractId": map[string]any{"$ref": "#/$defs/contractId"},
					"minimumVersion":          map[string]any{"$ref": "#/$defs/semver"},
					"maximumVersionExclusive": map[string]any{"$ref": "#/$defs/semver"},
				},
			},
			"peerEndpoint": map[string]any{"type": "object",
				"additionalProperties": false,
				"required":             []any{"carrier", "endpoint", "securityProfile"},
				"properties": map[string]any{"carrier": map[string]any{"enum": []any{"tcp", "quic", "unix", "windows-named-pipe"}},
					"endpoint": map[string]any{"type": "string",
						"minLength": 1,
						"maxLength": 2048,
					},
					"securityProfile": map[string]any{"const": "mtls"},
				},
			},
			"release": map[string]any{"type": "object",
				"additionalProperties": false,
				"required":             []any{"version", "sha256"},
				"properties": map[string]any{"version": map[string]any{"$ref": "#/$defs/semver"},
					"sha256": map[string]any{"$ref": "#/$defs/digest"},
				},
			},
			"registerRequest": map[string]any{"type": "object",
				"additionalProperties": false,
				"required":             []any{"contractVersion", "identity", "restEndpoint", "peerEndpoints", "release", "advertisedContracts", "acceptedContracts", "appliedGeneration", "ready"},
				"properties": map[string]any{"contractVersion": map[string]any{"const": "liapoldus.plugin-sdk.replica-lifecycle.v2"},
					"identity": map[string]any{"$ref": "#/$defs/identity"},
					"restEndpoint": map[string]any{"type": "string",
						"format":  "uri",
						"pattern": "^https://",
					},
					"peerEndpoints": map[string]any{"type": "array",
						"maxItems": 4,
						"items":    map[string]any{"$ref": "#/$defs/peerEndpoint"},
					},
					"release": map[string]any{"$ref": "#/$defs/release"},
					"advertisedContracts": map[string]any{"type": "array",
						"maxItems": 64,
						"items":    map[string]any{"$ref": "#/$defs/contractVersion"},
					},
					"acceptedContracts": map[string]any{"type": "array",
						"maxItems": 64,
						"items":    map[string]any{"$ref": "#/$defs/contractRange"},
					},
					"appliedGeneration": map[string]any{"type": "string",
						"maxLength": 256,
					},
					"ready": map[string]any{"type": "boolean"},
				},
			},
			"registerResponse": map[string]any{"type": "object",
				"additionalProperties": false,
				"required":             []any{"contractVersion", "identity", "serverTime", "leaseExpiresAt"},
				"properties": map[string]any{"contractVersion": map[string]any{"const": "liapoldus.plugin-sdk.replica-lifecycle.v2"},
					"identity": map[string]any{"$ref": "#/$defs/identity"},
					"serverTime": map[string]any{"type": "string",
						"format": "date-time",
					},
					"leaseExpiresAt": map[string]any{"type": "string",
						"format": "date-time",
					},
				},
			},
			"renewRequest": map[string]any{"type": "object",
				"additionalProperties": false,
				"required":             []any{"contractVersion", "identity", "appliedGeneration", "ready"},
				"properties": map[string]any{"contractVersion": map[string]any{"const": "liapoldus.plugin-sdk.replica-lifecycle.v2"},
					"identity": map[string]any{"$ref": "#/$defs/identity"},
					"appliedGeneration": map[string]any{"type": "string",
						"maxLength": 256,
					},
					"ready": map[string]any{"type": "boolean"},
				},
			},
			"renewResponse": map[string]any{"type": "object",
				"additionalProperties": false,
				"required":             []any{"contractVersion", "identity", "serverTime", "leaseExpiresAt"},
				"properties": map[string]any{"contractVersion": map[string]any{"const": "liapoldus.plugin-sdk.replica-lifecycle.v2"},
					"identity": map[string]any{"$ref": "#/$defs/identity"},
					"serverTime": map[string]any{"type": "string",
						"format": "date-time",
					},
					"leaseExpiresAt": map[string]any{"type": "string",
						"format": "date-time",
					},
				},
			},
			"deregisterRequest": map[string]any{"type": "object",
				"additionalProperties": false,
				"required":             []any{"contractVersion", "identity"},
				"properties": map[string]any{"contractVersion": map[string]any{"const": "liapoldus.plugin-sdk.replica-lifecycle.v2"},
					"identity": map[string]any{"$ref": "#/$defs/identity"},
				},
			},
			"deregisterResponse": map[string]any{"type": "object",
				"additionalProperties": false,
				"required":             []any{"contractVersion", "identity", "deregistered"},
				"properties": map[string]any{"contractVersion": map[string]any{"const": "liapoldus.plugin-sdk.replica-lifecycle.v2"},
					"identity":     map[string]any{"$ref": "#/$defs/identity"},
					"deregistered": map[string]any{"const": true},
				},
			},
		},
	}
}
